# version: "3.9"

# Docker Compose configuration for development environment
services:
  app:
    build:
      context: .
      args:
        - DEV=true
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_db_buffer &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=dev_db
      - DB_USER=dev_user
      - DB_PASSWORD=change_me
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=change_me
      - POSTGRES_DB=dev_db
      - POSTGRES_PORT=5432
    ports:
      - "5433:5432" # use 5433 on host to avoid conflicts - as of writing, we have psql in windows and docker

volumes:
  dev_db_data: